arch:
  - amd64
  - ppc64le
  
language: node_js

node_js:
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 0.10
  - 0.11
  - 0.12
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14 
  - 15
  - lts/*
  - node

script:
  - arch
